global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'db-handler'
    static_configs:
      - targets: ['db-handler:8084']
  - job_name: 'auth-handler'
    static_configs:
      - targets: ['auth-handler:8081']
  - job_name: 'file-handler'
    static_configs:
      - targets: ['file-handler:8083']
