version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    networks:
      - my-network
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    
  api:
    build: .
    container_name: db-handler-api
    environment:
      - MONGO_URI=mongodb://mongodb:mongodb@mongodb:27017
    networks:
      - my-network
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
